# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: woosh/proto/util/action.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dwoosh/proto/util/action.proto\x12\x0cwoosh.action*\x80\x01\n\x04Type\x12\x12\n\x0ekTypeUndefined\x10\x00\x12\x08\n\x04kNav\x10\x01\x12\r\n\tkStepCtrl\x10\x02\x12\x13\n\x0fkSecondposEnter\x10\x03\x12\x12\n\x0ekSecondposQuit\x10\x04\x12\n\n\x06kCarry\x10\x05\x12\t\n\x05kWait\x10\x06\x12\x0b\n\x07kCharge\x10\x07*\x91\x01\n\x05State\x12\x13\n\x0fkStateUndefined\x10\x00\x12\x11\n\rkRosExecuting\x10\x01\x12\x0f\n\x0bkRosWarning\x10\x02\x12\x0e\n\nkRosCancel\x10\x03\x12\x0f\n\x0bkRosSuccess\x10\x04\x12\x0f\n\x0bkRosFailure\x10\x05\x12\x0c\n\x08kSuspend\x10\n\x12\x0f\n\x0bkTraffiCtrl\x10\x0b*\x8d\x01\n\x05Order\x12\x13\n\x0fkOrderUndefined\x10\x00\x12\n\n\x06kStart\x10\x01\x12\n\n\x06kPause\x10\x02\x12\r\n\tkContinue\x10\x03\x12\x0b\n\x07kCancel\x10\x04\x12\x0c\n\x08kRecover\x10\x05\x12\x0e\n\nkWaitBreak\x10\x06\x12\x0b\n\x07kTmCtrl\x10\x07\x12\x10\n\x0ckReleaseCtrl\x10\x08\x42*\n\x12woosh.proto.actionB\x0f\x41\x63tionUtilProtoP\x00\xf8\x01\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'woosh.proto.util.action_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\022woosh.proto.actionB\017ActionUtilProtoP\000\370\001\001'
  _TYPE._serialized_start=48
  _TYPE._serialized_end=176
  _STATE._serialized_start=179
  _STATE._serialized_end=324
  _ORDER._serialized_start=327
  _ORDER._serialized_end=468
# @@protoc_insertion_point(module_scope)
