# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: woosh/proto/util/commu_pack.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!woosh/proto/util/commu_pack.proto\x12\x10woosh.commu_pack\x1a\x19google/protobuf/any.proto\"J\n\x0bMessagePack\x12\"\n\x04\x62ody\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\x12\n\n\x02ok\x18\x65 \x01(\x08\x12\x0b\n\x03msg\x18\x66 \x01(\t\"+\n\x0cSubscription\x12\x0b\n\x03sub\x18\x01 \x01(\x08\x12\x0e\n\x06topics\x18\x0b \x03(\t\"C\n\x0fRequestPackJson\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\"\n\x04\x62ody\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\"]\n\x10ResponsePackJson\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\"\n\x04\x62ody\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\x12\n\n\x02ok\x18\x65 \x01(\x08\x12\x0b\n\x03msg\x18\x66 \x01(\t\"B\n\x0eNotifyPackJson\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\"\n\x04\x62ody\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\"i\n\x0fMessagePackJson\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\"\n\x04\x62ody\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\x12\n\n\x02ok\x18\x65 \x01(\x08\x12\x0b\n\x03msg\x18\x66 \x01(\t\x12\x0b\n\x02sn\x18\xc9\x01 \x01(\x05\x42\x31\n\x16woosh.proto.commu_packB\x12\x43ommuPackUtilProtoP\x00\xf8\x01\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'woosh.proto.util.commu_pack_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\026woosh.proto.commu_packB\022CommuPackUtilProtoP\000\370\001\001'
  _MESSAGEPACK._serialized_start=82
  _MESSAGEPACK._serialized_end=156
  _SUBSCRIPTION._serialized_start=158
  _SUBSCRIPTION._serialized_end=201
  _REQUESTPACKJSON._serialized_start=203
  _REQUESTPACKJSON._serialized_end=270
  _RESPONSEPACKJSON._serialized_start=272
  _RESPONSEPACKJSON._serialized_end=365
  _NOTIFYPACKJSON._serialized_start=367
  _NOTIFYPACKJSON._serialized_end=433
  _MESSAGEPACKJSON._serialized_start=435
  _MESSAGEPACKJSON._serialized_end=540
# @@protoc_insertion_point(module_scope)
