# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: woosh/proto/util/common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dwoosh/proto/util/common.proto\x12\x0cwoosh.common\"\"\n\x04\x45num\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05\"-\n\x06Pose2D\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\r\n\x05theta\x18\x03 \x01(\x02\":\n\x04Pose\x12\"\n\x04pose\x18\x01 \x01(\x0b\x32\x14.woosh.common.Pose2D\x12\x0e\n\x06map_id\x18\x02 \x01(\r\"(\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"*\n\x07Vector3\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"8\n\nQuaternion\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x12\t\n\x01w\x18\x04 \x01(\x02\"(\n\x05Twist\x12\x0e\n\x06linear\x18\x01 \x01(\x02\x12\x0f\n\x07\x61ngular\x18\x02 \x01(\x02\"$\n\x07\x46ileMD5\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03md5\x18\x02 \x01(\t\"&\n\x08\x46ileData\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"(\n\nTimeBucket\x12\r\n\x05start\x18\x01 \x01(\x05\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x05\x42*\n\x12woosh.proto.commonB\x0f\x43ommonUtilProtoP\x00\xf8\x01\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'woosh.proto.util.common_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\022woosh.proto.commonB\017CommonUtilProtoP\000\370\001\001'
  _ENUM._serialized_start=47
  _ENUM._serialized_end=81
  _POSE2D._serialized_start=83
  _POSE2D._serialized_end=128
  _POSE._serialized_start=130
  _POSE._serialized_end=188
  _POINT._serialized_start=190
  _POINT._serialized_end=230
  _VECTOR3._serialized_start=232
  _VECTOR3._serialized_end=274
  _QUATERNION._serialized_start=276
  _QUATERNION._serialized_end=332
  _TWIST._serialized_start=334
  _TWIST._serialized_end=374
  _FILEMD5._serialized_start=376
  _FILEMD5._serialized_end=412
  _FILEDATA._serialized_start=414
  _FILEDATA._serialized_end=452
  _TIMEBUCKET._serialized_start=454
  _TIMEBUCKET._serialized_end=494
# @@protoc_insertion_point(module_scope)
