# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: woosh/proto/util/device.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dwoosh/proto/util/device.proto\x12\x0cwoosh.device*i\n\x04Type\x12\x12\n\x0ekTypeUndefined\x10\x00\x12\x0b\n\x07kCaller\x10\x01\x12\r\n\tkDetector\x10\x02\x12\x0b\n\x07kCtrler\x10\x03\x12\t\n\x05kFire\x10\x04\x12\t\n\x05kLift\x10\x05\x12\x0e\n\nkIndicator\x10\x06\x42*\n\x12woosh.proto.deviceB\x0f\x44\x65viceUtilProtoP\x00\xf8\x01\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'woosh.proto.util.device_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\022woosh.proto.deviceB\017DeviceUtilProtoP\000\370\001\001'
  _TYPE._serialized_start=47
  _TYPE._serialized_end=152
# @@protoc_insertion_point(module_scope)
