# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: woosh/proto/util/map.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1awoosh/proto/util/map.proto\x12\twoosh.map*l\n\nMarkerType\x12\x18\n\x14kMarkerTypeUndefined\x10\x00\x12\x0c\n\x08kStorage\x10\x01\x12\r\n\tkWormhole\x10\x02\x12\x0b\n\x07kBeacon\x10\x03\x12\n\n\x06kARTag\x10\x04\x12\x0e\n\nkReflector\x10\x05*\xed\x01\n\tFieldType\x12\x17\n\x13kFieldTypeUndefined\x10\x00\x12\x13\n\x0fkBidirectionWay\x10\x01\x12\x0e\n\nkSingleWay\x10\x02\x12\x0b\n\x07kOneWay\x10\x03\x12\r\n\tkCrossing\x10\x04\x12\x12\n\x0ekNarrowPassage\x10\x05\x12\x0b\n\x07kLocate\x10\x06\x12\t\n\x05kRamp\x10\x07\x12\t\n\x05kOdom\x10\x08\x12\r\n\tkAutoDoor\x10\t\x12\x0f\n\x0bkSpeedLimit\x10\n\x12\x0e\n\nkFireField\x10\x0b\x12\x0e\n\nkWarnField\x10\x0c\x12\x0f\n\x0bkGuideField\x10\r*D\n\x08PathType\x12\x16\n\x12kPathTypeUndefined\x10\x00\x12\r\n\tkMonoPath\x10\x01\x12\x11\n\rkBidirectPath\x10\x02\x42$\n\x0fwoosh.proto.mapB\x0cMapUtilProtoP\x00\xf8\x01\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'woosh.proto.util.map_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\017woosh.proto.mapB\014MapUtilProtoP\000\370\001\001'
  _MARKERTYPE._serialized_start=41
  _MARKERTYPE._serialized_end=149
  _FIELDTYPE._serialized_start=152
  _FIELDTYPE._serialized_end=389
  _PATHTYPE._serialized_start=391
  _PATHTYPE._serialized_end=459
# @@protoc_insertion_point(module_scope)
