# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: woosh/proto/util/navigation.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from woosh.proto.util import common_pb2 as woosh_dot_proto_dot_util_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!woosh/proto/util/navigation.proto\x12\twoosh.nav\x1a\x1dwoosh/proto/util/common.proto\"+\n\x04Path\x12#\n\x05poses\x18\x01 \x03(\x0b\x32\x14.woosh.common.Pose2D\"\x86\x02\n\x08PlanPath\x12\x1d\n\x04path\x18\x01 \x01(\x0b\x32\x0f.woosh.nav.Path\x12\x0e\n\x06map_id\x18\x02 \x01(\r\x12\x13\n\x0bwormhole_id\x18\x03 \x01(\r\x12\x13\n\x0b\x64\x65st_map_id\x18\x04 \x01(\r\x12$\n\x06target\x18\x05 \x01(\x0b\x32\x14.woosh.common.Pose2D\x12,\n\x07optimal\x18\n \x01(\x0e\x32\x1b.woosh.nav.PlanPath.Optimal\"M\n\x07Optimal\x12\x15\n\x11kOptimalUndefined\x10\x00\x12\x0c\n\x08kOptimal\x10\x01\x12\x10\n\x0ckDestOptimal\x10\x02\x12\x0b\n\x07kStrict\x10\t\"\x82\x01\n\tLocalPath\x12*\n\x06points\x18\x01 \x03(\x0b\x32\x1a.woosh.nav.LocalPath.Point\x12\x0c\n\x04time\x18\x0b \x01(\x05\x1a;\n\x05Point\x12\"\n\x04pose\x18\x01 \x01(\x0b\x32\x14.woosh.common.Pose2D\x12\x0e\n\x06\x65xpend\x18\x02 \x01(\r\"\xa4\x01\n\x0bModeSetting\x12 \n\x04type\x18\x01 \x01(\x0e\x32\x12.woosh.nav.ArrType\x12\x1d\n\x04mode\x18\x02 \x01(\x0e\x32\x0f.woosh.nav.Mode\x12\x14\n\x0cwait_timeout\x18\x03 \x01(\r\x12\x11\n\tmax_speed\x18\x04 \x01(\x02\x12\x19\n\x11permitted_passage\x18\x0b \x01(\x08\x12\x10\n\x08\x63\x61pacity\x18\x0c \x01(\x05*z\n\x04Mode\x12\x12\n\x0ekModeUndefined\x10\x00\x12\n\n\x06kAvoid\x10\x01\x12\x0c\n\x08kNavWait\x10\x02\x12\x0c\n\x08kTimeout\x10\x03\x12\r\n\tkOvertime\x10\x04\x12\x0b\n\x07kNarrow\x10\n\x12\r\n\tkMagnetic\x10\x0b\x12\x0b\n\x07kQrcode\x10\x0c*;\n\x07\x41rrType\x12\x15\n\x11kArrTypeUndefined\x10\x00\x12\n\n\x06kVague\x10\x01\x12\r\n\tkAccurate\x10\x02\x42$\n\x0fwoosh.proto.navB\x0cNavUtilProtoP\x00\xf8\x01\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'woosh.proto.util.navigation_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\017woosh.proto.navB\014NavUtilProtoP\000\370\001\001'
  _MODE._serialized_start=689
  _MODE._serialized_end=811
  _ARRTYPE._serialized_start=813
  _ARRTYPE._serialized_end=872
  _PATH._serialized_start=79
  _PATH._serialized_end=122
  _PLANPATH._serialized_start=125
  _PLANPATH._serialized_end=387
  _PLANPATH_OPTIMAL._serialized_start=310
  _PLANPATH_OPTIMAL._serialized_end=387
  _LOCALPATH._serialized_start=390
  _LOCALPATH._serialized_end=520
  _LOCALPATH_POINT._serialized_start=461
  _LOCALPATH_POINT._serialized_end=520
  _MODESETTING._serialized_start=523
  _MODESETTING._serialized_end=687
# @@protoc_insertion_point(module_scope)
