# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: woosh/proto/util/robot.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cwoosh/proto/util/robot.proto\x12\x0bwoosh.robot*\xb3\x01\n\x04Type\x12\x12\n\x0ekTypeUndefined\x10\x00\x12\x12\n\x0ekBaseRobot_200\x10\x01\x12\x18\n\x14kPalletLiftRobot_500\x10\x0b\x12\x17\n\x13kShelfLiftRobot_500\x10\x15\x12\x15\n\x11kTractorRobot_500\x10\x1f\x12\x14\n\x10kRollerRobot_500\x10)\x12\x11\n\rkComplexRobot\x10\x32\x12\x10\n\x0ckArmRobot_14\x10=*\x94\x01\n\x05State\x12\x13\n\x0fkStateUndefined\x10\x00\x12\x0b\n\x07kUninit\x10\x01\x12\t\n\x05kIdle\x10\x02\x12\x0c\n\x08kParking\x10\x03\x12\t\n\x05kTask\x10\x04\x12\x0c\n\x08kWarning\x10\x05\x12\n\n\x06kFault\x10\x06\x12\x0e\n\nkFollowing\x10\x07\x12\r\n\tkCharging\x10\x08\x12\x0c\n\x08kMapping\x10\t*O\n\x0b\x43ontrolMode\x12\x19\n\x15kControlModeUndefined\x10\x00\x12\t\n\x05kAuto\x10\x01\x12\x0b\n\x07kManual\x10\x02\x12\r\n\tkMaintain\x10\x03*U\n\x08WorkMode\x12\x16\n\x12kWorkModeUndefined\x10\x00\x12\x0f\n\x0bkDeployMode\x10\x01\x12\r\n\tkTaskMode\x10\x02\x12\x11\n\rkScheduleMode\x10\x03*>\n\tFootPrint\x12\r\n\tkOriginal\x10\x00\x12\x0b\n\x07kExpand\x10\x01\x12\n\n\x06kSpare\x10\x02\x12\t\n\x05kDock\x10\x03\x42(\n\x11woosh.proto.robotB\x0eRobotUtilProtoP\x00\xf8\x01\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'woosh.proto.util.robot_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021woosh.proto.robotB\016RobotUtilProtoP\000\370\001\001'
  _TYPE._serialized_start=46
  _TYPE._serialized_end=225
  _STATE._serialized_start=228
  _STATE._serialized_end=376
  _CONTROLMODE._serialized_start=378
  _CONTROLMODE._serialized_end=457
  _WORKMODE._serialized_start=459
  _WORKMODE._serialized_end=544
  _FOOTPRINT._serialized_start=546
  _FOOTPRINT._serialized_end=608
# @@protoc_insertion_point(module_scope)
