# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: woosh/proto/util/task.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bwoosh/proto/util/task.proto\x12\nwoosh.task*@\n\tDirection\x12\x17\n\x13kDirectionUndefined\x10\x00\x12\x0c\n\x08kFeeding\x10\x01\x12\x0c\n\x08kCutting\x10\x02*L\n\x04Type\x12\x12\n\x0ekTypeUndefined\x10\x00\x12\t\n\x05kPick\x10\x01\x12\x0c\n\x08kParking\x10\x02\x12\x0b\n\x07kCharge\x10\x03\x12\n\n\x06kCarry\x10\x04*\x9c\x01\n\x05State\x12\x13\n\x0fkStateUndefined\x10\x00\x12\t\n\x05kInit\x10\x01\x12\n\n\x06kReady\x10\x02\x12\x0e\n\nkExecuting\x10\x03\x12\x0b\n\x07kPaused\x10\x04\x12\x0f\n\x0bkActionWait\x10\x05\x12\r\n\tkTaskWait\x10\x06\x12\x0e\n\nkCompleted\x10\x07\x12\r\n\tkCanceled\x10\x08\x12\x0b\n\x07kFailed\x10\tB&\n\x10woosh.proto.taskB\rTaskUtilProtoP\x00\xf8\x01\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'woosh.proto.util.task_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\020woosh.proto.taskB\rTaskUtilProtoP\000\370\001\001'
  _DIRECTION._serialized_start=43
  _DIRECTION._serialized_end=107
  _TYPE._serialized_start=109
  _TYPE._serialized_end=185
  _STATE._serialized_start=188
  _STATE._serialized_end=344
# @@protoc_insertion_point(module_scope)
