# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: woosh/proto/map/storage_edit.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from woosh.proto.map import mark_pb2 as woosh_dot_proto_dot_map_dot_mark__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"woosh/proto/map/storage_edit.proto\x12\x16woosh.map.mark.storage\x1a\x1awoosh/proto/map/mark.proto\"2\n\x06\x43reate\x12(\n\x07storage\x18\x01 \x01(\x0b\x32\x17.woosh.map.mark.Storage\"\x14\n\x06\x44\x65lete\x12\n\n\x02no\x18\x01 \x01(\t\"2\n\x06Update\x12(\n\x07storage\x18\x01 \x01(\x0b\x32\x17.woosh.map.mark.Storage\"\x12\n\x04\x46ind\x12\n\n\x02no\x18\x01 \x01(\t\"\n\n\x08StoragesB1\n\x18woosh.proto.storage.editB\x10StorageEditProtoP\x00\xf8\x01\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'woosh.proto.map.storage_edit_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\030woosh.proto.storage.editB\020StorageEditProtoP\000\370\001\001'
  _CREATE._serialized_start=90
  _CREATE._serialized_end=140
  _DELETE._serialized_start=142
  _DELETE._serialized_end=162
  _UPDATE._serialized_start=164
  _UPDATE._serialized_end=214
  _FIND._serialized_start=216
  _FIND._serialized_end=234
  _STORAGES._serialized_start=236
  _STORAGES._serialized_end=246
# @@protoc_insertion_point(module_scope)
