# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: woosh/proto/robot/robot_setting.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%woosh/proto/robot/robot_setting.proto\x12\x13woosh.robot.setting\"8\n\x08Identity\x12\x13\n\x08robot_id\x18\xc7\x01 \x01(\rH\x00\x12\x0c\n\x04name\x18\x01 \x01(\tB\t\n\x07request\"B\n\x06Server\x12\x13\n\x08robot_id\x18\xc7\x01 \x01(\rH\x00\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\rB\t\n\x07request\";\n\nAutoCharge\x12\x13\n\x08robot_id\x18\xc7\x01 \x01(\rH\x00\x12\r\n\x05\x61llow\x18\x01 \x01(\x08\x42\t\n\x07request\"9\n\x08\x41utoPark\x12\x13\n\x08robot_id\x18\xc7\x01 \x01(\rH\x00\x12\r\n\x05\x61llow\x18\x01 \x01(\x08\x42\t\n\x07request\";\n\nGoodsCheck\x12\x13\n\x08robot_id\x18\xc7\x01 \x01(\rH\x00\x12\r\n\x05\x61llow\x18\x01 \x01(\x08\x42\t\n\x07request\"_\n\x05Power\x12\x13\n\x08robot_id\x18\xc7\x01 \x01(\rH\x00\x12\r\n\x05\x61larm\x18\x01 \x01(\r\x12\x0b\n\x03low\x18\x02 \x01(\r\x12\x0c\n\x04idle\x18\x03 \x01(\r\x12\x0c\n\x04\x66ull\x18\x04 \x01(\rB\t\n\x07request\"E\n\x05Sound\x12\x13\n\x08robot_id\x18\xc7\x01 \x01(\rH\x00\x12\x0c\n\x04mute\x18\x01 \x01(\x08\x12\x0e\n\x06volume\x18\x02 \x01(\rB\t\n\x07requestB+\n\x11woosh.proto.robotB\x11RobotSettingProtoP\x00\xf8\x01\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'woosh.proto.robot.robot_setting_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021woosh.proto.robotB\021RobotSettingProtoP\000\370\001\001'
  _IDENTITY._serialized_start=62
  _IDENTITY._serialized_end=118
  _SERVER._serialized_start=120
  _SERVER._serialized_end=186
  _AUTOCHARGE._serialized_start=188
  _AUTOCHARGE._serialized_end=247
  _AUTOPARK._serialized_start=249
  _AUTOPARK._serialized_end=306
  _GOODSCHECK._serialized_start=308
  _GOODSCHECK._serialized_end=367
  _POWER._serialized_start=369
  _POWER._serialized_end=464
  _SOUND._serialized_start=466
  _SOUND._serialized_end=535
# @@protoc_insertion_point(module_scope)
