# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: woosh/proto/ros/ros_pack.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from woosh.proto.ros import action_pb2 as woosh_dot_proto_dot_ros_dot_action__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ewoosh/proto/ros/ros_pack.proto\x12\twoosh.ros\x1a\x1cwoosh/proto/ros/action.proto\"\xcc\x03\n\nCallAction\x12\x39\n\x0e\x63harge_control\x18\x01 \x01(\x0b\x32\x1f.woosh.ros.action.ChargeControlH\x00\x12\x35\n\x0clift_control\x18\x02 \x01(\x0b\x32\x1d.woosh.ros.action.LiftControlH\x00\x12\x37\n\rlift_control2\x18\x03 \x01(\x0b\x32\x1e.woosh.ros.action.LiftControl2H\x00\x12\x35\n\x0cstep_control\x18\x04 \x01(\x0b\x32\x1d.woosh.ros.action.StepControlH\x00\x12\x37\n\rlift_control3\x18\x05 \x01(\x0b\x32\x1e.woosh.ros.action.LiftControl3H\x00\x12/\n\tmove_base\x18\x33 \x01(\x0b\x32\x1a.woosh.ros.action.MoveBaseH\x00\x12\x34\n\x08nav_mode\x18\x34 \x01(\x0b\x32 .woosh.ros.action.NavigationModeH\x00\x12\x32\n\nany_action\x18\xc9\x01 \x01(\x0b\x32\x1b.woosh.ros.action.AnyActionH\x00\x42\x08\n\x06\x61\x63tion\"V\n\x08\x46\x65\x65\x64\x62\x61\x63k\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\x1f\n\x05state\x18\x0b \x01(\x0e\x32\x10.woosh.ros.State\x12\x0c\n\x04\x63ode\x18\x0c \x01(\x04\x12\x0b\n\x03msg\x18\r \x01(\t\"-\n\tFeedbacks\x12 \n\x03\x66\x62s\x18\x01 \x03(\x0b\x32\x13.woosh.ros.Feedback*\xdb\x01\n\x05State\x12\x0c\n\x08kRosNone\x10\x00\x12\x17\n\nkRosCancel\x10\xfe\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x18\n\x0bkRosFailure\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x0f\n\x0bkRosSuccess\x10\x01\x12\x11\n\rkRosExecuting\x10\x02\x12\r\n\tkRosPause\x10\x03\x12\x13\n\x0fkRosPauseFailed\x10\x04\x12\x15\n\x11kRosExecuteFailed\x10\x05\x12\x0e\n\nkRosErrMsg\x10\n\x12\x10\n\x0ckRosWiFiCode\x10\x64\x12\x10\n\x0ckRosWiFiJson\x10\x65\x42\'\n\x0fwoosh.proto.rosB\x0fRosRequestProtoP\x00\xf8\x01\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'woosh.proto.ros.ros_pack_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\017woosh.proto.rosB\017RosRequestProtoP\000\370\001\001'
  _STATE._serialized_start=674
  _STATE._serialized_end=893
  _CALLACTION._serialized_start=76
  _CALLACTION._serialized_end=536
  _FEEDBACK._serialized_start=538
  _FEEDBACK._serialized_end=624
  _FEEDBACKS._serialized_start=626
  _FEEDBACKS._serialized_end=671
# @@protoc_insertion_point(module_scope)
