# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: woosh/proto/dispatch/robot_commu.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&woosh/proto/dispatch/robot_commu.proto\x12\x14woosh.dispatch.robot\".\n\x06Online\x12\n\n\x02id\x18\x01 \x01(\r\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\r\"\x15\n\x07Offline\x12\n\n\x02id\x18\x01 \x01(\rB:\n\x1awoosh.proto.dispatch.robotB\x17\x44ispatchRobotCommuProtoP\x00\xf8\x01\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'woosh.proto.dispatch.robot_commu_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\032woosh.proto.dispatch.robotB\027DispatchRobotCommuProtoP\000\370\001\001'
  _ONLINE._serialized_start=64
  _ONLINE._serialized_end=110
  _OFFLINE._serialized_start=112
  _OFFLINE._serialized_end=133
# @@protoc_insertion_point(module_scope)
