# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: woosh/proto/device/beacon.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fwoosh/proto/device/beacon.proto\x12\x13woosh.device.beacon\"1\n\x06\x42\x65\x61\x63on\x12\n\n\x02id\x18\x01 \x01(\r\x12\r\n\x05power\x18\x02 \x01(\x02\x12\x0c\n\x04time\x18\x0b \x01(\x05\"7\n\x07\x42\x65\x61\x63ons\x12,\n\x07\x62\x65\x61\x63ons\x18\x01 \x03(\x0b\x32\x1b.woosh.device.beacon.BeaconB*\n\x12woosh.proto.deviceB\x0f\x42\x65\x61\x63onInfoProtoP\x00\xf8\x01\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'woosh.proto.device.beacon_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\022woosh.proto.deviceB\017BeaconInfoProtoP\000\370\001\001'
  _BEACON._serialized_start=56
  _BEACON._serialized_end=105
  _BEACONS._serialized_start=107
  _BEACONS._serialized_end=162
# @@protoc_insertion_point(module_scope)
