# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: woosh/proto/device/elevator.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!woosh/proto/device/elevator.proto\x12\x0cwoosh.device\"\x18\n\x08\x45levator\x12\x0c\n\x04name\x18\x01 \x01(\tB,\n\x12woosh.proto.deviceB\x11\x45levatorInfoProtoP\x00\xf8\x01\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'woosh.proto.device.elevator_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\022woosh.proto.deviceB\021ElevatorInfoProtoP\000\370\001\001'
  _ELEVATOR._serialized_start=51
  _ELEVATOR._serialized_end=75
# @@protoc_insertion_point(module_scope)
