# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: woosh/proto/device/sensor.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fwoosh/proto/device/sensor.proto\x12\x13woosh.device.sensor\"#\n\x04\x46ire\x12\x0c\n\x04warn\x18\x01 \x01(\x08\x12\r\n\x05\x64rill\x18\x02 \x01(\x08\"\r\n\x0bGetFireInfo\"3\n\x08\x46ireTime\x12\x12\n\nstart_time\x18\x01 \x01(\x05\x12\x13\n\x0bremain_time\x18\x02 \x01(\x05\"\x11\n\x0fGetFireTimeInfo\"?\n\x0fSetFireTimeInfo\x12,\n\x05\x66time\x18\x01 \x01(\x0b\x32\x1d.woosh.device.sensor.FireTime\"\x17\n\x04Lift\x12\x0f\n\x07grating\x18\x01 \x01(\x08\"\r\n\x0bGetLiftInfoB*\n\x12woosh.proto.deviceB\x0fSensorInfoProtoP\x00\xf8\x01\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'woosh.proto.device.sensor_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\022woosh.proto.deviceB\017SensorInfoProtoP\000\370\001\001'
  _FIRE._serialized_start=56
  _FIRE._serialized_end=91
  _GETFIREINFO._serialized_start=93
  _GETFIREINFO._serialized_end=106
  _FIRETIME._serialized_start=108
  _FIRETIME._serialized_end=159
  _GETFIRETIMEINFO._serialized_start=161
  _GETFIRETIMEINFO._serialized_end=178
  _SETFIRETIMEINFO._serialized_start=180
  _SETFIRETIMEINFO._serialized_end=243
  _LIFT._serialized_start=245
  _LIFT._serialized_end=268
  _GETLIFTINFO._serialized_start=270
  _GETLIFTINFO._serialized_end=283
# @@protoc_insertion_point(module_scope)
